# Site settings
title: The Code Less Traveled
header-img: img/home-bg.png
email: hambrice@uab.edu
copyright_name: hambrice
description: > # this means to ignore newlines until "baseurl:"
  Figuring out my next steps in life, one error message at a time.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hambrice
learn_profile: hambrice
email_username: hambrice@uab.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
